config/routes.rb
Rails.application.routes.draw do
  get "about", to: "about#index"

  get"password", to: "passwords#edit", as: :edit_password
  patch"password", to:"passwords#update"
  
  get "sign_up", to:"registrations#new"
  post "sign_up", to:"registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to:"sessions#create"
  
  delete "logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get"password/reset/edit", to: "password_resets#edit"
  post"password/reset/edit", to: "password_resets#update"
  
  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # validates_length_of :username, 
  #   :minimum => 5, :maximum => 50, 
  #   presence: true,
  #   uniqueness: true
  #   resources :users, only: [:new, :create]
  # has_secure_password

  validates :email, presence: true
end
# u1=User.create({username:"hannah", email:"hannah@gmail", password:"password"})
# u2=User.create({username:"kim", email:"kim@gmail", password:"passwordforkim"})

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  
  def set_current_user
    flash.now[:notice]="Logged in successfully"
    flash.now[:alert]="Invalid email or password"
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end
  def require_user_logged_in!
    redirect_to sign_in_path, alert: "You must be signed in to do that." if Current.user.nil?
  end
end

app/controllers/main_controller.rb
class MainController < AboutController
  def index
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end 

  def create
    @uset= User.find_by(email: params[:email])

    if @user.present?
      PasswordMailer.with(user: @user).reset.deliver_now
  
    end
  redirect_to root_path, notice: "If an account with this email is found, we will send a link to reset your password"
  end

  def edit
    @user= User.find_signed(params[:token], purpose: "password_reset")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, alert: "Your token has expired, please try again."
  end
end


# F6tsL6WnoqzoShCfoaBdg-api key
# NcOD1B5WzrlnaWPpctQYu1DoIRIwCEJNDXtmilk6DSY-API secret key

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!
  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password Updated!"
    else 
      render :edit
    end
  end



    private
    
  def password_params
    params.require(:user).permit(:password)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user=User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      session[:user_id]=@user.id
      redirect_to root_path, notice: "Successfully  Created Account"
    else
      flash[:alert] ="Oops! Something went wrong!"
      render :new
  end
end

  private
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:email])
      session[:user_id] = user.id 
      redirect_to root_path, notice: "Logged in successfully"
    else
      flash[:alert]= "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Successfully Logged Out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  
  def new
    @user = User.new
  end

  def create
    # @user = User.new(username: params[:username], email: params[:email], password: params[:password])
    @user = User.new(user_params)
  end
end

  #   if @user.save
  #     redirect_to new_user_path
  #   else
  #     render :new
  #   end
  # end

  # def edit
  #   @user = User.find(params[:id])
  # end

  # def update
  #   @user = User.find(params[:id])
  #   if @user.update(user_params)
  #     redirect_to new_user_path
  #   else
  #     render :edit
  #   end
  # end

  # private
  # def user_params
  #   params.require(:user).permit(:username, :email, :password)
  # end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRuby3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render partial: "shared/navbar" =%>
    <div class="container">
      <%= render partial: "shared/flash"%>
    <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
<h1>Welcome to Scheduled Tweets</h1>
  </div>

  

app/views/password_resets/edit.html.erb
<h1> Reset your password </h1>

<%= form_with url: password_reset_edit_path do |form|%>

<div class ="mb-3">
<%= form.label :Password%>
<%= form.password_field :password , class:"form-control", placeholder: "1!Password" %>
</div>
  
<div class ="mb-3">
<%= form.submit "Reset Password",  class: "btn btn-primary"%>
</div>
  
<%end%>

app/views/password_resets/new.html.erb
<h1> Forgot your password? </h1>

<%= form_with url: password_reset_path do |form|%>

<div class ="mb-3">
<%= form.label :Email%>
<%= form.text_field :email , class:"form-control", placeholder: "KimK@gmail.com"%>
</div>
  
<div class ="mb-3">
<%= form.submit "Reset Password",  class: "btn btn-primary"%>
</div>
  
<%end%>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role ="alert">
    <%= flash[:notice]%>
  </div>
<% end %>
  
<% if flash[:alert] %> 
  <div class="alert alert-warning mt-4"  role ="alert">
    <%= flash[:alert]%>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    

    <%= link_to "Navbar", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link"%>
        </li>
      </ul>


    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <% if Current.user%>
        <li class="nav-item">
        <%=link_to Current.user.username, edit_password_path, class: "nav-link"%>
        </li>
        <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary"%>
      <%else%>
        <li class="nav-item">
        <%= link_to "Login", sign_in_path%>
        </li>
        <li class="nav-item">
        <%= link_to "Sign Up", sign_up_path, class: "nav-link"%>
        </li>
      <%end%>
    </ul>
      

    </div>
  </div>
</nav>

app/views/users/new.html.erb
<%# <h2>User Form</h2>
<form action="/users" method="post" accept-charset="UTF-8" >
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>
  <%#<label for="username">username:</label>
  <input type="text" id="username" name="user[username]"><br><br>
  <label for="email">email:</label>
  <input type="text" id="email" name="user[email]"><br><br>
  <label for="password">password:</label>
  <input type="password" id="password" name="user[password]"><br><br>
  <input type="submit" value="Submit">
</form> %>
<%# <%= form_tag('/users', method: "post") do %> 
  <%# <%= label_tag(:username, 'username') %> 
  <%# <%= text_field_tag(:username) %> 
  <%# <%= label_tag(:email, 'email') %> 
  <%# <%= text_field_tag(:email) %> 
  <%# <%= label_tag(:password, 'password') %> 
  <%# <%= password_field_tag(:password) %> 
  <%# <%= submit_tag('Submit') %> 
<%# <% end %> 
<h1>New User Form</h1>

<%= render partial: "user", locals: {user: @user} %>